services:
  blitz:
    build: .
    image: blitz:latest
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - blitz-backend

networks:
  blitz-backend:
    driver: bridge